version: '3.8'

services:
  ocoffee:
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/ocoffee
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:5432/${PG_DB}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocoffee.rule=Host(`ocoffee.creachtheo.fr`)"
      - "traefik.http.routers.ocoffee.entrypoints=websecure"
      - "traefik.http.routers.ocoffee.tls.certresolver=myresolver"
      - "traefik.http.services.ocoffee.loadbalancer.server.port=${PORT}"
    networks:
      - traefik-public  # Utilisation du réseau géré par Traefik

networks:
  traefik-public:
    external: true  # Réseau externe existant géré par Traefik
