version: '3.8'

services:
  app:
    build: .
    expose:
      - ${PORT}
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:5432/${PG_DATABASE}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocoffee.rule=Host(`ocoffee.creachtheo.fr`)"
      - "traefik.http.routers.ocoffee.entrypoints=websecure"
      - "traefik.http.routers.ocoffee.tls.certresolver=myresolver"
      - "traefik.http.services.ocoffee.loadbalancer.server.port=${PORT}"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
