version: '3.8'
services:
  app:
    build: .
    expose:
      - ${PORT}
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:5432/${PG_DATABASE}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocoffee.rule=Host(`ocoffee.creachtheo.fr`)"
      - "traefik.http.routers.ocoffee.entrypoints=websecure"
      - "traefik.http.routers.ocoffee.tls=true"
      - "traefik.http.routers.ocoffee.tls.certresolver=myresolver"
      - "traefik.http.services.ocoffee.loadbalancer.server.port=${PORT}"
    networks:
      - traefik-public

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=creach.t@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    networks:
      - traefik-public

networks:
  traefik-public:
    external: false

volumes:
  traefik-certificates:
