version: '3.8'

services:
  ocoffee:
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/ocoffee
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:5432/${PG_DATABASE}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`ocoffee.creachtheo.fr`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=${PORT}"
    networks:
